"""Added reset password fields

Revision ID: 4a8c6c4dc451
Revises: e2470973db23
Create Date: 2024-06-11 07:41:13.726896

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a8c6c4dc451"
down_revision: Union[str, None] = "e2470973db23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("reset_password_code", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("reset_password_code_expiry_date", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reset_password_code_expiry_date")
    op.drop_column("users", "reset_password_code")
    # ### end Alembic commands ###
