"""Added referrals

Revision ID: f23331e973f8
Revises: 4a8c6c4dc451
Create Date: 2025-10-25 22:36:06.154882

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f23331e973f8"
down_revision: Union[str, None] = "4a8c6c4dc451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount_coupons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("referrer_user_id", sa.Integer(), nullable=True),
        sa.Column("discount_percentage", sa.Integer(), nullable=True),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["referrer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discount_coupons_id"), "discount_coupons", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_discount_coupons_referrer_user_id"),
        "discount_coupons",
        ["referrer_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_discount_coupons_user_id"),
        "discount_coupons",
        ["user_id"],
        unique=False,
    )
    op.add_column("orders", sa.Column("final_price", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("referral_code", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_users_referral_code"), "users", ["referral_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_referral_code"), table_name="users")
    op.drop_column("users", "referral_code")
    op.drop_column("orders", "final_price")
    op.drop_index(op.f("ix_discount_coupons_user_id"), table_name="discount_coupons")
    op.drop_index(
        op.f("ix_discount_coupons_referrer_user_id"), table_name="discount_coupons"
    )
    op.drop_index(op.f("ix_discount_coupons_id"), table_name="discount_coupons")
    op.drop_table("discount_coupons")
    # ### end Alembic commands ###
